[tool.poetry]
name = "renag"
version = "0.4.4"
description = "A Regex based linter tool that works for any language and works exclusively with custom linting rules."
authors = ["Ryan <ryanpeach@icloud.com>"]

[tool.poetry.dependencies]
python = "^3.7"
pyparsing = "^2.4.7"
GitPython = "^3.1.17"

[tool.poetry.dev-dependencies]
pytest = "^5.2"
iregex = "^0.2.1"
pre-commit = "^2.12.1"
flake8 = "^3.9.1"
flake8-docstrings = "^1.6.0"
mypy = "^0.812"
black = "^21.5b0"
isort = "^5.8.0"
coverage = "^5.5"
Sphinx = "^3.5.4"
codecov = "^2.1.11"
m2r2 = "^0.2.7"
sphinx_autodoc_typehints = "^1.12.0"
pydocstyle = "^6.0.0"
bumpversion = "^0.6.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.isort]
profile = "black"
multi_line_output = 3

[tool.poetry.scripts]
renag = 'renag.__main__:main'
